### ISSUE TITLE
Evaluation issues regarding memory overflow on GPU

### ISSUE THREAD

**Issue by HaodiFan** [elias-ramzi/ROADMAP#11]
Hi, 

After having trained the model with SOP dataset, I tried to use the ckpt to run evaluate.py. The cmd i used is : ` python evaluate.py --config /home/zhijue/experiments/ROADMAP/sop_ROADMAP_128_sota/weights/epoch_100.ckpt --bs 128`. 
The result is like this:
> 09/08/2022 02:16:27 PM - INFO - running k-nn with k=2048
09/08/2022 02:16:27 PM - INFO - embedding dimensionality is 512
Traceback (most recent call last):
  File "evaluate.py", line 95, in <module>
    metrics = load_and_evaluate(
  File "evaluate.py", line 51, in load_and_evaluate
    metrics = eng.evaluate(
  File "/home/zhijue/project/models/ROADMAP/roadmap/utils/get_set_random_state.py", line 32, in wrapper
    output = func(*args, **kwargs)
  File "/home/zhijue/project/models/ROADMAP/roadmap/engine/evaluate.py", line 141, in evaluate
    return tester.test(
  File "/home/zhijue/anaconda3/envs/roadmap/lib/python3.8/site-packages/pytorch_metric_learning/testers/base_tester.py", line 306, in test
    self.do_knn_and_accuracies(
  File "/home/zhijue/anaconda3/envs/roadmap/lib/python3.8/site-packages/pytorch_metric_learning/testers/global_embedding_space.py", line 21, in do_knn_and_accuracies
    a = self.accuracy_calculator.get_accuracy(
  File "/home/zhijue/project/models/ROADMAP/roadmap/engine/accuracy_calculator.py", line 155, in get_accuracy
    knn_indices, knn_distances = get_knn(
  File "/home/zhijue/project/models/ROADMAP/roadmap/engine/get_knn.py", line 16, in get_knn
    distances, indices = get_knn_faiss(references, queries, num_k)
  File "/home/zhijue/project/models/ROADMAP/roadmap/engine/get_knn.py", line 47, in get_knn_faiss
    index.add(references)
  File "/home/zhijue/anaconda3/envs/roadmap/lib/python3.8/site-packages/faiss/contrib/torch_utils.py", line 96, in torch_replacement_add
    return self.add_numpy(x)
  File "/home/zhijue/anaconda3/envs/roadmap/lib/python3.8/site-packages/faiss/__init__.py", line 104, in replacement_add
    self.add_c(n, swig_ptr(x))
  File "/home/zhijue/anaconda3/envs/roadmap/lib/python3.8/site-packages/faiss/swigfaiss.py", line 4313, in add
    return _swigfaiss.IndexReplicas_add(self, n, x)
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/StandardGpuResources.cpp:410: Error: 'err == cudaSuccess' failed: Failed to cudaMalloc 123908096 bytes on device 0 (error 2 out of memory
Outstanding allocations:
Alloc type TemporaryMemoryBuffer: 1 allocations, 1610612736 bytes

It seems like the model only let me to do evaluation on single GPU. Is it possible for it to perform on multiple GPU?

My GPU config is: 

> +-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
|   0  NVIDIA GeForce ...  On   | 00000000:41:00.0 Off |                  N/A |
| 22%   35C    P8     5W / 250W |    344MiB / 11264MiB |      0%      Default |

**Comment by HaodiFan** [comment]
I tried with a smaller BS (BS=64) and it worked.

**Comment by elias-ramzi** [comment]
Hi,
I am glad it worked.

Maybe you can also try using the torch version for the `get_knn` function, by modifying in the following file: `roadmap/engine/get_knn.py` and changing the default argument `with_faiss` from `True` to `False`.

Hope this helps!
